### ISSUE TITLE
Some questions about how to use the PyGradFlow code.

### ISSUE THREAD

**Issue by cuixi94** [chrhansk/pygradflow#24]
I don't understand your code, so I would like to ask you how to use PyGradFlow to solve nonlinear problems in Python. Can you give me a simple example of solving a nonlinear problem using PyGradFlow?
Thanks,

**Comment by chrhansk** [comment]
Hey @cuixi94. Thank you for your interest in the code. I added an example to the documentation [here](
https://pygradflow.readthedocs.io/en/latest/). I hope that helps.

Alternatively, if you are interested in a more mature solver, you can use [Ipopt](https://github.com/coin-or/Ipopt) which also comes with a [python](https://github.com/mechmotum/cyipopt/) interface.
